version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "80:80"
    volumes:
      - ..:/var/www/html

  db:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: moddb
      MYSQL_USER: vsmoddb
      MYSQL_PASSWORD: vsmoddb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ../db:/docker-entrypoint-initdb.d:ro

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"

volumes:
  mysql-data:
